name: NPM Release
on:
    release:
        types: [created]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.release.target_commitish }}

            - name: Validate release
              id: release
              uses: manovotny/github-releases-for-automated-package-publishing-action@v2.0.1

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  always-auth: true
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Publish version
              if: steps.release.outputs.tag == ''
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish tagged version
              if: steps.release.outputs.tag != ''
              run: npm publish --tag ${{ steps.release.outputs.tag }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}